In [20]:
import pandas as pd
import numpy as np
!pip install category_encoders

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: category_encoders in /home/Cristian/.local/lib/python3.10/site-packages (2.5.0)
Requirement already satisfied: patsy>=0.5.1 in /home/Cristian/.local/lib/python3.10/site-packages (from category_encoders) (0.5.2)
Requirement already satisfied: numpy>=1.14.0 in /home/Cristian/.local/lib/python3.10/site-packages (from category_encoders) (1.22.4)
Requirement already satisfied: pandas>=1.0.5 in /home/Cristian/.local/lib/python3.10/site-packages (from category_encoders) (1.4.2)
Requirement already satisfied: statsmodels>=0.9.0 in /home/Cristian/.local/lib/python3.10/site-packages (from category_encoders) (0.13.2)
Requirement already satisfied: scikit-learn>=0.20.0 in /home/Cristian/.local/lib/python3.10/site-packages (from category_encoders) (1.1.1)
Requirement already satisfied: scipy>=1.0.0 in /home/Cristian/.local/lib/python3.10/site-packages (from category_encoders) (1.8.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/Cristian/.local/lib/python3.10/site-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/Cristian/.local/lib/python3.10/site-packages (from pandas>=1.0.5->category_encoders) (2022.1)
Requirement already satisfied: six in /usr/lib/python3.10/site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/Cristian/.local/lib/python3.10/site-packages (from scikit-learn>=0.20.0->category_encoders) (3.1.0)
Requirement already satisfied: joblib>=1.0.0 in /home/Cristian/.local/lib/python3.10/site-packages (from scikit-learn>=0.20.0->category_encoders) (1.1.0)
Requirement already satisfied: packaging>=21.3 in /usr/lib/python3.10/site-packages (from statsmodels>=0.9.0->category_encoders) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3.10/site-packages (from packaging>=21.3->statsmodels>=0.9.0->category_encoders) (2.4.7)

In [2]:
# Read dataset 
df = pd.read_csv('kidney_disease.csv')

In [3]:
# Describe dataset
df

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [4]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [5]:
def normalize(x):
    """
    Function for remove nondesired characters from data
    """
    if type(x) == str:
        try:
            x = float(x)
        except Exception as e:
            x = ''.join(i for i in x.split() if i.isalnum())
        if not x:
            x = np.nan
    return x

In [6]:
# Making maping of columns
maping_y = {'notckd': 0, 'ckd': 1}

In [7]:
# Mapping and cleaning data
y = y.apply(lambda x: maping_y[normalize(x)])
for column in X.columns:
    X[column].apply(lambda x: normalize(x))

In [8]:
# Normalize 
for column in X.columns:
    array_df = X[column]
    new_array = array_df.apply(normalize)
    X[column] = new_array

In [9]:
categorical_columns = ['rbc', 'pc', 'ba', 'pcc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'wc']

In [10]:
X = X.drop(categorical_columns, axis=1)

In [11]:
X

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,rc
0,0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,NaN,NaN,15.4,44.0,5.2
1,1,7.0,50.0,1.020,4.0,0.0,NaN,18.0,0.8,NaN,NaN,11.3,38.0,NaN
2,2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,NaN,NaN,9.6,31.0,NaN
3,3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,2.5,11.2,32.0,3.9
4,4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,NaN,NaN,11.6,35.0,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,140.0,49.0,0.5,150.0,4.9,15.7,47.0,4.9
396,396,42.0,70.0,1.025,0.0,0.0,75.0,31.0,1.2,141.0,3.5,16.5,54.0,6.2
397,397,12.0,80.0,1.020,0.0,0.0,100.0,26.0,0.6,137.0,4.4,15.8,49.0,5.4
398,398,17.0,60.0,1.025,0.0,0.0,114.0,50.0,1.0,135.0,4.9,14.2,51.0,5.9
399,399,58.0,80.0,1.025,0.0,0.0,131.0,18.0,1.1,141.0,3.5,15.8,53.0,6.1

In [12]:
from sklearn.impute import SimpleImputer

In [37]:
# Create an instance of the SimpleImputer with the strategy set as median.
from sklearn.impute import SimpleImputer
si_mean = SimpleImputer(strategy='mean')
si_median = SimpleImputer(strategy='median')
si_most_frequent = SimpleImputer(strategy='most_frequent')
si_constant = SimpleImputer(strategy='constant', fill_value=0)

In [38]:
si_mean_X_data = si_mean.fit_transform(X)
si_median_X_data = si_median.fit_transform(X)
si_most_frequent_X_data = si_most_frequent.fit_transform(X)
si_constant_X_data = si_constant.fit_transform(X)

In [39]:
# Importing Models
from sklearn.linear_model import LogisticRegression 
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [40]:
# Initializing Models
knn = KNN()
lr = LogisticRegression(max_iter=5000)
gnb = GaussianNB()

In [41]:
# Creating Table
Table = {'Model':[], 'Technique':[], 'Accuracy':[]}

In [42]:
# si_mean

# Split data in test and train part for si_mean
X_train, X_test, y_train, y_test = train_test_split(si_mean_X_data, y)


lr.fit(X_train,y_train)
knn.fit(X_train,y_train)
gnb.fit(X_train,y_train)

lr_score = lr.score(X_test, y_test)
knn_score = knn.score(X_test, y_test)
gnb_score = gnb.score(X_test, y_test)

Table['Model'].append('Linear Regression')
Table['Model'].append('KNN')
Table['Model'].append('Naive Bayes')

Table['Technique'].append('si_mean')
Table['Technique'].append('si_mean')
Table['Technique'].append('si_mean')

Table['Accuracy'].append(lr_score)
Table['Accuracy'].append(knn_score)
Table['Accuracy'].append(gnb_score)

In [43]:
# si_median

# Split data in test and train part for si_mean
X_train, X_test, y_train, y_test = train_test_split(si_median_X_data, y)


lr.fit(X_train,y_train)
knn.fit(X_train,y_train)
gnb.fit(X_train,y_train)

lr_score = lr.score(X_test, y_test)
knn_score = knn.score(X_test, y_test)
gnb_score = gnb.score(X_test, y_test)

Table['Model'].append('Linear Regression')
Table['Model'].append('KNN')
Table['Model'].append('Naive Bayes')

Table['Technique'].append('si_median')
Table['Technique'].append('si_median')
Table['Technique'].append('si_median')

Table['Accuracy'].append(lr_score)
Table['Accuracy'].append(knn_score)
Table['Accuracy'].append(gnb_score)

In [44]:
# si_most_frequent

# Split data in test and train part for si_mean
X_train, X_test, y_train, y_test = train_test_split(si_most_frequent_X_data, y)


lr.fit(X_train,y_train)
knn.fit(X_train,y_train)
gnb.fit(X_train,y_train)

lr_score = lr.score(X_test, y_test)
knn_score = knn.score(X_test, y_test)
gnb_score = gnb.score(X_test, y_test)

Table['Model'].append('Linear Regression')
Table['Model'].append('KNN')
Table['Model'].append('Naive Bayes')

Table['Technique'].append('si_most_frequent')
Table['Technique'].append('si_most_frequent')
Table['Technique'].append('si_most_frequent')

Table['Accuracy'].append(lr_score)
Table['Accuracy'].append(knn_score)
Table['Accuracy'].append(gnb_score)

In [45]:
# si_constant

# Split data in test and train part for si_mean
X_train, X_test, y_train, y_test = train_test_split(si_constant_X_data, y)


lr.fit(X_train,y_train)
knn.fit(X_train,y_train)
gnb.fit(X_train,y_train)

lr_score = lr.score(X_test, y_test)
knn_score = knn.score(X_test, y_test)
gnb_score = gnb.score(X_test, y_test)

Table['Model'].append('Linear Regression')
Table['Model'].append('KNN')
Table['Model'].append('Naive Bayes')

Table['Technique'].append('si_constant')
Table['Technique'].append('si_constant')
Table['Technique'].append('si_constant')

Table['Accuracy'].append(lr_score)
Table['Accuracy'].append(knn_score)
Table['Accuracy'].append(gnb_score)

In [48]:
table_df = pd.DataFrame(Table)

In [49]:
table_df

                Model         Technique  Accuracy
0   Linear Regression           si_mean      1.00
1                 KNN           si_mean      0.99
2         Naive Bayes           si_mean      0.97
3   Linear Regression         si_median      1.00
4                 KNN         si_median      0.99
5         Naive Bayes         si_median      0.95
6   Linear Regression  si_most_frequent      1.00
7                 KNN  si_most_frequent      0.99
8         Naive Bayes  si_most_frequent      0.94
9   Linear Regression       si_constant      1.00
10                KNN       si_constant      0.99
11        Naive Bayes       si_constant      0.95